
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.VBox vBox;
	private global::Gtk.MenuBar MenuBar;
	private global::Gtk.Toolbar ToolBar;
	private global::Gtk.HPaned hPane;
	private global::Gtk.ScrolledWindow TreeViewScrolledWindow;
	private global::Gtk.TreeView TreeView;
	private global::Gtk.ScrolledWindow TextViewScrolledWindow;
	private global::Gtk.TextView TextView;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Open"), global::Mono.Unix.Catalog.GetString ("Open file..."), "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), global::Mono.Unix.Catalog.GetString ("Quit application..."), "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.quitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 1024;
		this.HeightRequest = 768;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("CecIL");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-properties", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.Modal = true;
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vBox = new global::Gtk.VBox ();
		this.vBox.Name = "vBox";
		this.vBox.Spacing = 6;
		// Container child vBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name=\'MenuBar\'><menu name=\'FileAction\' action=\'FileAction\'><menuitem" +
			" name=\'openAction\' action=\'openAction\'/><separator/><menuitem name=\'quitAction\' " +
			"action=\'quitAction\'/></menu></menubar></ui>");
		this.MenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MenuBar")));
		this.MenuBar.Name = "MenuBar";
		this.vBox.Add (this.MenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vBox [this.MenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name=\'ToolBar\'><toolitem name=\'openAction\' action=\'openAction\'/><sep" +
			"arator/><toolitem name=\'quitAction\' action=\'quitAction\'/></toolbar></ui>");
		this.ToolBar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/ToolBar")));
		this.ToolBar.Name = "ToolBar";
		this.ToolBar.ShowArrow = false;
		this.vBox.Add (this.ToolBar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vBox [this.ToolBar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vBox.Gtk.Box+BoxChild
		this.hPane = new global::Gtk.HPaned ();
		this.hPane.CanFocus = true;
		this.hPane.Name = "hPane";
		this.hPane.Position = 200;
		// Container child hPane.Gtk.Paned+PanedChild
		this.TreeViewScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.TreeViewScrolledWindow.Name = "TreeViewScrolledWindow";
		this.TreeViewScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child TreeViewScrolledWindow.Gtk.Container+ContainerChild
		this.TreeView = new global::Gtk.TreeView ();
		this.TreeView.CanFocus = true;
		this.TreeView.Name = "TreeView";
		this.TreeViewScrolledWindow.Add (this.TreeView);
		this.hPane.Add (this.TreeViewScrolledWindow);
		global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hPane [this.TreeViewScrolledWindow]));
		w5.Resize = false;
		// Container child hPane.Gtk.Paned+PanedChild
		this.TextViewScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.TextViewScrolledWindow.Name = "TextViewScrolledWindow";
		this.TextViewScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child TextViewScrolledWindow.Gtk.Container+ContainerChild
		this.TextView = new global::Gtk.TextView ();
		this.TextView.CanFocus = true;
		this.TextView.Name = "TextView";
		this.TextView.Editable = false;
		this.TextViewScrolledWindow.Add (this.TextView);
		this.hPane.Add (this.TextViewScrolledWindow);
		this.vBox.Add (this.hPane);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vBox [this.hPane]));
		w8.Position = 2;
		this.Add (this.vBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1032;
		this.DefaultHeight = 800;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpen);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuit);
	}
}
